### ISSUE TITLE
dataretrieval.nwis.get_record() returns one value instead of all records when no start date specified

### ISSUE THREAD

**Issue by putmanannie** [USGS-python/dataretrieval#28]
A query like the following (no start date included):

    import dataretrieval.nwis as nwis
    SCi = nwis.get_record(sites = '09383100', service = 'dv', parameterCd = ["00095", "90095"])

returns a single record (it seems to be the most recent?):

                               00095_Mean 00095_Mean_cd   site_no
    datetime                                                     
    2000-09-29 00:00:00+00:00       740.0             A  09383100

whereas a query that includes a start date, like the following;

    SCi = nwis.get_record(sites = '09383100', service = 'dv', parameterCd = ["00095", "90095"], start = '1900-01-01')

returns a dataframe with many records (1344 rows for this particular gage, to be exact). 

This seems like unexpected behavior. I would expect that retrievals with no date constraints would return all available records. Of course, the workaround is just to enter a start date well before you would expect records, but the unexpected behavior did temporarily cause some confusion.

**Comment by thodson-usgs** [comment]
This is the default behavior of NWIS. If you send no date range to the REST server, NWIS only returns 1 date.  I think we want to retain the behavior for now (to prevent people from carelessly pulling massive datasets from NWIS), but I'll note it in the function documentation.
