### ISSUE TITLE
fixed: cannot specify HUC for site summary search criteria

### ISSUE THREAD

**Issue by putmanannie** [USGS-python/dataretrieval#29]
When I initially tried to retrieve Lower Colorado River Basin total dissolved solids site summary data by hydrologic unit code (HUC), I got the error:

    import dataretrieval.nwis as nwis
    siteinfo = nwis.get_info(huc='15', parameterCd=["70301", "70300", "00095", "90095"])

    _error: 'Query must specify a major filter: sites, stateCd, bBox'_

This led me to lines 282 and 283 in nwis.py:

        if not any(key in kwargs for key in ['sites', 'stateCd', 'bBox']):
            raise TypeError('Query must specify a major filter: sites, stateCd, bBox')

which I changed to:

        if not any(key in kwargs for key in ['sites', 'stateCd', 'bBox', 'huc']):
            raise TypeError('Query must specify a major filter: sites, stateCd, bBox, huc')

which fixed the problem. I'm submitting this as a bug fix, in case anyone else has run into this particular error.

**Comment by thodson-usgs** [comment]
Thanks. Will fix this for the next release.
