### ISSUE TITLE
WQP TODO: implement other services like Organization, Activity, etc.

### ISSUE THREAD

**Issue by jbousquin** [USGS-python/dataretrieval#35]
wqp.py lines 6-7 has this as a TODO. Seems easy enough to implement brute force following what was done for stations. How are these for function names (url term), and any that are missing or may have conflicts/complications?
- what_organizations ('Organization')
- what_projects          ('Project')
- what_activities         ('Activity')
- what_detection_limits ('ResultDetectionQuantitationLimit')
- what_habitat_metrics ('BiologicalMetric')
- what_project_weights ('ProjectMonitoringLocationWeighting')
- what_activity_metrics ('ActivityMetric')*

All but activity metrics appear queriable using location (may just not be activity metrics where I tested) but they are not all queriable by siteid. For subsets of results (narrow, biological metadata) just pass dataProfile as a get_results param.

**Comment by thodson-usgs** [comment]
Closed
