### ISSUE TITLE
Poorly parsed return for 'pmcodes = nwis.get_pmcodes(parameterCd='All')'

### ISSUE THREAD

**Issue by putmanannie** [USGS-python/dataretrieval#38]
So, I want to return a pandas dataframe of all of the parameter codes. Like the documentation suggests, I used:
`pmcodes = nwis.get_pmcodes(parameterCd='All')`

I realize that this should return a tuple of metadata and the dataframe. The issue is with the dataframe - it seems like it doesn't get parsed properly upon return, perhaps because the separators are ',' and not ', ' (with a space following the comma). I'm thinking this might be the case because the column headers in the dataframe look like this:

` In [37]:pmcodes[0].columns
Out[37]: Index(['parameter_cd', 'parameter_group_nm,casrn,srsname,parameter_units,parameter_nm'], dtype='object')`

Most of the actual information (parameter_code, parameter_group, etc) is actually assigned as a tuple to the index. I'm currently writing a little workaround, but thought it might be nice to get it straightened out in the function return.

**Comment by putmanannie** [comment]
Another note - it seems like the headers also come back in the wrong order. The data returns as is displayed on the web (see example of a row below):

`52271	Organics, other	(20R)-24-Ethyl-5.alpha.(H),14.alpha.(H),17.alpha.(H)-cholestane, bed sediment smaller than 2 millimeters, wet sieved (native water), field, recoverable, dry weight, micro	62446-14-4		ug/kg`

but the headers come back in a different order:

`parameter_cd	parameter_group_nm	casrn	srsname	parameter_units	parameter_nm`

This means stitching the headers and rows together is not straightforward. 

Any idea why this might be? is it an issue with what NWIS returns?

**Comment by thodson-usgs** [comment]
You can view what NWIS returns using this url:
`pmcodes, meta = nwis.get_pmcodes(parameterCd='All')
meta.url`
...interesting, some rows are delimited by tabs, while others are a mix of tabs and commas. That poses a parsing challenge.
Should have more luck if we request the data as a json, rather than the rdb.

**Comment by thodson-usgs** [comment]
Everything should parse correctly now, but the fields are still out of order, so it's currently on the user to rename them.
Not sure if this is worth hacking together a fix as NWIS may tinker with the interface, but I'm open to suggestions.

**Comment by putmanannie** [comment]
Great on the parsing, but bummer on the headers. That's weird. 

Although it would be ideal for the headers to come back in the right order, you're right that it will break whenever NWIS folks make changes. For that reason, I'd say not worth it. Maybe just add the note about the headers not coming back in the right order to the documentation as a warning to users, with an example of how to rename headers? (e.g., df.rename(columns={'key': 'value'}, inplace = True).
