### ISSUE TITLE
test_get_water_use_allegheny failing

### ISSUE THREAD

**Issue by oconnelljon** [USGS-python/dataretrieval#39]
I cloned the repo and attached the tests to VS Codes built in test manager and all of them passed except for "test_get_water_use_allegheny."  I tracked the error to a piece of regex in _read_rdb in nwis.py.  The regex is producing multiple of the same values in a list and when that list is passed to pd.read_csv as a list of names for the columns, Pandas errors out saying 
`ValueError: Duplicate names are not allowed.`

Line 715 of nwis.py producing error:
`fields = re.split("[,\t]", rdb.splitlines()[count])`

Possible solution, passes test:  Change regex to split only on '\t'
`fields = re.split("\t", rdb.splitlines()[count])`

Operating system
Windows 10 Enterprise 10.0.19042 Build 19042 x64

Full error message:
	`./waterservices_test.py::test_get_water_use_allegheny Failed: [undefined]ValueError: Duplicate names are not allowed.
	requests_mock = <requests_mock.mocker.Mocker object at 0x0000028BE2783610>`

		def test_get_water_use_allegheny(requests_mock):
			"""Tests get_discharge_measurements method correctly generates the request url and returns the result in a
			DataFrame"""
			format = "rdb"
			request_url = 'https://nwis.waterdata.usgs.gov/PA/nwis/water_use?rdb_compression=value&format=rdb&wu_year=ALL' \
						  '&wu_category=ALL&wu_county=003&wu_area=county'
			response_file_path = 'data/water_use_allegheny.txt'
			mock_request(requests_mock, request_url, response_file_path)
	>       df, md = get_water_use(state="PA", counties="003")

	waterservices_test.py:208: 
	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
	..\dataretrieval\nwis.py:496: in get_water_use
		return _read_rdb(response.text), _set_metadata(response)
	..\dataretrieval\nwis.py:718: in _read_rdb
		df = pd.read_csv(StringIO(rdb), delimiter='\t', skiprows=count + 2,
	..\.venv\lib\site-packages\pandas\util\_decorators.py:311: in wrapper
		return func(*args, **kwargs)
	..\.venv\lib\site-packages\pandas\io\parsers\readers.py:586: in read_csv
		return _read(filepath_or_buffer, kwds)
	..\.venv\lib\site-packages\pandas\io\parsers\readers.py:479: in _read
		_validate_names(kwds.get("names", None))
	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

	names = ['state_cd', 'state_name', 'county_cd', 'county_nm', 'year', 'Total Population total population of area', ...]

		def _validate_names(names):
			"""
			Raise ValueError if the `names` parameter contains duplicates or has an
			invalid data type.
		
			Parameters
			----------
			names : array-like or None
				An array containing a list of the names used for the output DataFrame.
		
			Raises
			------
			ValueError
				If names are not unique or are not ordered (e.g. set).
			"""
			if names is not None:
				if len(names) != len(set(names)):
	>               raise ValueError("Duplicate names are not allowed.")
	E               ValueError: Duplicate names are not allowed.

	..\.venv\lib\site-packages\pandas\io\parsers\readers.py:460: ValueError

**Comment by jsta** [comment]
This is solved by #43
