### ISSUE TITLE
Datetime Records Missing if time code is not present

### ISSUE THREAD

**Issue by SarkenD** [USGS-python/dataretrieval#47]
Hello- It would be great if the retrieval code be modified to pull date and time columns using the get_record function. It appears that the current method provides a date record if date **AND** a time column is filled out.  When you run the retrieval program, there are 176,000+ records where datetime is returned as null.  The function should pull the date and time column separately.   The user can concatenate these together if need be using pandas.

Example Below: Shows a water level value for date sampled of 1983-04-21.  Unfortunately, the dataretrieval scripts pulls together a datetime column with a null value if time is missing.  

![image](https://user-images.githubusercontent.com/107429063/173412310-f5a87eb7-bf52-4706-9968-6b66c3645c67.png)

![image](https://user-images.githubusercontent.com/107429063/173413462-db3a7b32-5a6e-4666-83c5-7a6fd09edf2a.png)

please reach out to me if you need more info.  Sdressler@usgs.gov

**Comment by thodson-usgs** [comment]
@elbeejay, We've handled the timestamp issues for some services, though not all. Seems like we need to think about a more general solution.

**Comment by elbeejay** [comment]
Thanks for noting and describing the issue all. I'll have a look next week and come up with a solution, @SarkenD's proposal in the first post looks reasonable to me so will just double check to make sure that doesn't break anything else before implementing. @thodson-usgs I'll make sure any changes don't break existing functionality, but will introduce deprecation warnings if/as necessary.
