### ISSUE TITLE
streamflow data from all NWIS stations for coastal zones

### ISSUE THREAD

**Issue by prasanjitdash** [USGS-python/dataretrieval#50]
Thank you for this effort, the package works as intended. However, I have a need that I cannot address myself in the current framework. Can someone please provide some pointer to the following questions:

1) If I want to download `streamflow data` for all stations near coasts, how can I generate a list of these coastal stations?

2) Is there an XML or configuration file that lists the ids for all stations and associated site info?. This will be useful to just plot station locations on a coastal application. (as in the map below for NDBC standard meteorological stations).  I explored the USGS site but could not find a complete listing of the stations ids; perhaps 'm missing something.

3) Is there a list of `parameterCd`? For example, `00060` = `discharge` in the demo code. What about other parameters?

![image](https://user-images.githubusercontent.com/16653595/181120814-c8af940d-91de-4530-981d-048ccba7b3ad.png)

**Comment by elbeejay** [comment]
1. I think you'd need to come up with your own definition of "coastal" and then you can proceed any number of ways. Some ideas off the top of my head are: defining bounding boxes to get stations within defined areas (``bBox`` argument); using a list of states, counties, or HUC codes to call `get_info()` and then filtering based on lat/lon coordinates of the stations to get the subset of those you consider to be "coastal"
2. You can get the IDs and site information for states from NWIS using the `get_info()` function in the `nwis.py` file
3. You can search for parameter codes here: https://help.waterdata.usgs.gov/codes-and-parameters/

I hope that helps @prasanjitdash, let me know if we can close this issue.
