### ISSUE TITLE
no dataretrival.codes module 

### ISSUE THREAD

**Issue by conster303** [USGS-python/dataretrieval#57]
to use data retrieval I need the codes.py module and it is not in this repo

**Comment by elbeejay** [comment]
Hi @conster303, thanks for opening an issue. Can you provide a bit more context about the problem you're having? It'd be helpful to know if/how you've installed `dataretrieval` locally on your machine (via conda, pip, from source, something else?). Additionally, if you could provide the snippet of code you are running and getting an error with, as well as the corresponding error message, that'd be helpful in trying to diagnose the problem.

**Comment by thodson-usgs** [comment]
@conster303, be sure to include which version of `dataretrieval` you have. `codes.py` might be from an older version.

**Comment by conster303** [comment]
Thanks! It looks like the version I cloned (https://github.com/USGS-python/dataretrieval.git) has the 'calls.py' in the nwis.py and utils.py modules, but calls.py is not in this version, instead there is timezones.py  so i just renamed everything that has calls.py to timezones

**Comment by elbeejay** [comment]
If you want to keep your local copy as up to date as possible @conster303 I'd suggest cloning the repository using `git` and periodically running `git pull` to get the latest version of the code. Manual fixes may leave you with unstable code that we will be unable to help you troubleshoot or fix in the future.
