### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by belencito27** [USGS-python/dataretrieval#6]
Hi,
I am getting this error as I run pip install 

ERROR: Could not find a version that satisfies the requirement dataretrieval (from versions: none)
ERROR: No matching distribution found for dataretrieval

Is dataretrieval for python still available?

Thanks for the reply.

**Comment by thodson-usgs** [comment]
Sorry for not seeing this sooner. I wasn't able to replicate this issue. Are you still unable to install from pip?
