### ISSUE TITLE
Better documentation of time zones and time zone awareness of objects would be helpful

### ISSUE THREAD

**Issue by ddileonardo** [USGS-python/dataretrieval#61]
It is unclear to a new user how the time zone is represented in the retrieved data. This is in large part due the a lack of documentation of the pytz module (at least what I could find). From what I can tell the time information is retrieved in the following way:

- Times are given as time zone aware with the time zone indicated by pytz.FixedOffset from UTC with the amount of the fixed offset representing minutes (i.e. pytz.FixedOffset(300) is 300 minutes = 5 hours)
- Time zones are also listed in the site info
- Example time stamp retrieved using get_record: time = Timestamp('2022-10-01 00:00:00-0500', tz='pytz.FixedOffset(-300)')
- Time zones can be converted using the pandas conversion tools
- For the example, time. tz_convert(tz=None), removes the time zone information and returns a UTC time --> Timestamp('2022-10-01 05:00:00')
- time.tz_convert(tz='utc') yields the same UTC time, but with the time zone information still attached --> Timestamp('2022-10-01 05:00:00+0000', tz='UTC')
- time.tz_convert(tz='America/New_York') converts the time to a new time zone --> Timestamp('2022-10-01 01:00:00-0400', tz='America/New_York')

If this is correct and helpful, please feel free to use in the documentation.

**Comment by elbeejay** [comment]
This is a great point @ddileonardo, I'll review the individual bullet points as I address issue #60 and put together PR #62 to make sure it is more clear how time zones are being handled and what the output means.
