### ISSUE TITLE
Correct parameter code reference table

### ISSUE THREAD

**Issue by kevinrosa** [USGS-python/dataretrieval#63]
I'm referencing [this table](https://help.waterdata.usgs.gov/code/parameter_cd_query?fmt=rdb&group_cd=PHY&inline=true) which defines `00060` as mean daily and `00061` as instantaneous discharge. 
```
00060	Physical	Discharge, cubic feet per second	Not checked	Mean	1 Day					 	Stream flow, mean. daily	ft3/s
00061	Physical	Discharge, instantaneous, cubic feet per second	Agree							 	Stream flow, instantaneous	ft3/s
```

However, when I downloading the instantaneous data services, I get back `00060`, not `00061`:
```python
df = nwis.get_record(sites='02376033', service='iv', start='2022-12-15')
print(df)

                           00045 00045_cd   site_no   00060 00060_cd  00065 00065_cd
datetime                                                                            
2022-12-15 08:45:00-06:00    NaN      NaN  02376033  3590.0        P   3.00        P
2022-12-15 09:00:00-06:00    0.0        P  02376033  3730.0        P   3.29        P
2022-12-15 09:15:00-06:00    0.0        P  02376033  3770.0        P   3.27        P
2022-12-15 09:30:00-06:00    0.0        P  02376033  3760.0        P   3.25        P
2022-12-15 09:45:00-06:00    0.0        P  02376033  3760.0        P   3.25        P
2022-12-15 10:00:00-06:00    0.0        P  02376033  3810.0        P   3.25        P
2022-12-15 10:15:00-06:00    0.0        P  02376033  3820.0        P   3.22        P
```

Am I reading the parameter code table wrong? Or the nwis dataframe wrong?

Here's the dataretrieval version I'm using with Python 3.9.13:
```
    package                    |            build
    ---------------------------|-----------------
    dataretrieval-0.7          |     pyhd8ed1ab_0          19 KB  conda-forge
```

**Comment by elbeejay** [comment]
@kevinrosa I don't have an exact answer for you yet, but I can tell you the following:

- The parameter code in the `dataretrieval` dataframes is what the NWIS API returns when that request is made; the package itself doesn't set the parameter code values. I did check and found that there is no data returned under the `00061` parameter code. I checked this using the [REST URL Generation Tool](https://waterservices.usgs.gov/rest/IV-Test-Tool.html) which returns this [XML file](https://waterservices.usgs.gov/nwis/iv/?format=waterml,2.0&sites=02376033&parameterCd=00060&siteStatus=all). If you try to construct a query with the `00061` parameter code, you get a [mostly empty XML file](https://waterservices.usgs.gov/nwis/iv/?format=waterml,2.0&sites=02376033&parameterCd=00061&siteStatus=all). I can confirm that `dataretrieval` is not assigning the parameter code to the dataframe, and the result you provided matches what the R version of `dataretrieval` also returns when the analogous function call is made.
- However, I don't have a ready answer as to why the NWIS API returns the parameter code `00060` for this query, as opposed to `00061` per the table you referenced. I'll work on identifying this and will get back to you once I've got an answer.

**Comment by elbeejay** [comment]
@kevinrosa the discrepancy between the documentation and the returned parameter code is apparently the result of historical USGS procedures in terms of data entry. The parameter code `00060` can refer to many different kinds of discharge, despite what the documentation for the parameter codes might say. So the values you are getting from your query are clearly discharge values, and given the timestamps and the queries they must be instantaneous discharge values.

**Comment by elbeejay** [comment]
Sorry, I did not mean to close this in the event you may have any follow-up questions.

**Comment by kevinrosa** [comment]
Ok great, thank you @elbeejay for the clarification.
