### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by thodson-usgs** [USGS-python/dataretrieval#64]
@elbeejay it has fixed the original issue. Maybe unrelated, but when I try to get the data from  **all** the sites in Maryland, it gives me an error related to parsing the JSON. My assumption is maybe the `site` is too large and the webAPI responds with an error (?) which fails to be parsed. Is there any way to have better error messages? e.g. area is too large for fetching data?

_Originally posted by @SorooshMani-NOAA in https://github.com/USGS-python/dataretrieval/issues/62#issuecomment-1357882119_

**Comment by SorooshMani-NOAA** [comment]
@thodson-usgs, sorry for the late reply, yes the comment from @elbeejay covers my use-case. Thanks!
