### ISSUE TITLE
Discrepancy between GitHub tag and PyPI version

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [USGS-python/dataretrieval#66]
The GitHub repository is tagged as `v1.0.0` however the version on PyPI is still at `0.8`:

https://github.com/USGS-python/dataretrieval/releases/tag/v1.0.0
vs
https://github.com/USGS-python/dataretrieval/blob/46eb1dd08ef96901644658a85fa88735c0c387e4/setup.py#L3-L4

**Comment by elbeejay** [comment]
@thodson-usgs released v1.0.1 and it deployed to pypi so release now matches pypi.

**Comment by thodson-usgs** [comment]
Forgot to close this in the commit.
