### ISSUE TITLE
Typo in project.toml

### ISSUE THREAD

**Issue by elbeejay** [USGS-python/dataretrieval#84]
Don't recall where we'd decided version information would live, but either way the current reference in `project.toml` looks wrong.

[Line 44](https://github.com/USGS-python/dataretrieval/blob/ba4ddef7e0476b3aac9d65307c605ee59863a6a9/pyproject.toml#L44):

```
write_to = "ratingcurve/_version.py"
```

**Comment by thodson-usgs** [comment]
oh dear! I'm juggling too many software releases. Thank you @elbeejay.

**Comment by thodson-usgs** [comment]
I should be assigning you to review these things, eh?

**Comment by elbeejay** [comment]
Up to you, it was small enough that I might have missed it in any case. Just glad it's on the books for a fix now
